### ISSUE TITLE
Do not show Fee in New Page

### ISSUE THREAD

**Issue by vuamitom** [vuamitom/Ghost#11]
![image](https://user-images.githubusercontent.com/633538/66470875-a08b3000-eab4-11e9-975c-6ac0a82c18af.png)

**Comment by vuamitom** [comment]
![image](https://user-images.githubusercontent.com/633538/66475912-7fc7d800-eabe-11e9-9546-1ce561ba2269.png)

Cái này dẫn tới bug ko save page được

**Comment by khuevu** [comment]
Fixed. Committed thang len Ghost-Admin/subscription roi nhe. PR to merge: https://github.com/vuamitom/Ghost/pull/13
