### ISSUE TITLE
Create register api for reader

### ISSUE THREAD

**Issue by vuamitom** [vuamitom/Ghost#2]
Similar to what happen when accepting invitation email. Only without invitation token

POST `/api/v2/finpub/readers`

References:
[https://github.com/vuamitom/Ghost/blob/master/core/server/services/invitations/accept.js](https://github.com/vuamitom/Ghost/blob/master/core/server/services/invitations/accept.js)

**Comment by vuamitom** [comment]
User registered should be created with Reader role (#3)

**Comment by vuamitom** [comment]
@khuevu  tích hợp api này vào ui nhé #8

**Comment by khuevu** [comment]
Done
