### ISSUE TITLE
Create frontend helper tag to list stock codes

### ISSUE THREAD

**Issue by vuamitom** [vuamitom/Ghost#5]
Provide frontend stock list helper tag.  `filter="kind:1"` 

```
               {{#get "tags" filter="kind:1" include="count.posts" order="count.posts desc" limit="6"}}
			{{#foreach tags}}
				<a href="{{url}}">{{name}} | {{count.posts}} posts</a>
    		{{/foreach}}
		{{/get}}
```

**Comment by vuamitom** [comment]
@kidphys   anh coi cái syntax ở trên nhé. .

**Comment by vuamitom** [comment]
tag nào company anh cứ đặt tên bình thường nhé. Ko cần có prefix gì. Nó sẽ check list company rồi fill vào meta_title, meta_description luôn.

**Comment by kidphys** [comment]
Sao lại filter="kind=1" hơi khó hiểu?

**Comment by vuamitom** [comment]
`filter="kind:1"`. filter là 1 option support bở ghost rồi, nó nhận input là NQL format. Syntax đầy đủ của nó trong cái link này https://github.com/NexesJS/NQL-Lang/blob/master/test/parser.test.js 

Còn em thêm 1 column `kind` cho `tag`, 1 là tag type Company.  https://github.com/vuamitom/Ghost/blob/member-signup/core/server/models/tag.js#L4

**Comment by vuamitom** [comment]
@kidphys Phần này tích hợp được chưa anh.
